#!/bin/bash

# Download terraform provider docs to consume them locally.
# Requires: curl, unzip

AUTHOR="${1:-hashicorp}" # or "digitaloceal", "databricks", "Snowflake-Labs", etc. Any terraform registry namespace or GitHub organization should work
PROVIDER="${2:-aws}"     # or "google", "azure", ...etc. See https://registry.terraform.io/browse/providers
REFS="${3:-heads}"       # or "tags"
VERSION="${4:-main}"     # or "v4.44.0"

TERRADOC_DOWNLOAD_DIR_PREFIX="/tmp"
TERRADOC_DOWNLOAD_DIR="terraform-provider-${PROVIDER}-${VERSION}"

if ! [[ -d "${TERRADOC_DOWNLOAD_DIR_PREFIX}/${TERRADOC_DOWNLOAD_DIR}" ]]; then
	curl -Lo "${TERRADOC_DOWNLOAD_DIR_PREFIX}/${TERRADOC_DOWNLOAD_DIR}.zip" "https://github.com/${AUTHOR}/terraform-provider-${PROVIDER}/archive/refs/${REFS}/${VERSION}.zip"
	unzip "${TERRADOC_DOWNLOAD_DIR_PREFIX}/${TERRADOC_DOWNLOAD_DIR}.zip" */docs/* -d "${TERRADOC_DOWNLOAD_DIR_PREFIX}/${TERRADOC_DOWNLOAD_DIR}"
fi

${EDITOR:-vim} "${TERRADOC_DOWNLOAD_DIR_PREFIX}/${TERRADOC_DOWNLOAD_DIR}"
